name: Continuous Delivery

on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy React Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to Firebase
        run: yarn firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project "$PROJECT_ID"

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}